Cicd pipleine
AOT-Technologies/forms-flow-ai-web-components pull request #12
Opened 2023-02-09 08:28 UTC by AbijithS-aot

2023-02-09 08:39 UTC, kiran-aot approved these changes

2023-02-09 08:39 UTC, kiran-aot commented
looks good to me

2023-02-09 08:41 UTC, sreehari-aot requested changes

2023-02-09 08:41 UTC, sreehari-aot commented on .github/workflows/forms-flow-web-components-cd.yml
> +      - run: npm ci --force
is force install necessary?

2023-02-09 08:41 UTC, sreehari-aot commented on forms-flow-webcomponent/.gitignore
> +.parcel-cache
try `.parcel-cache/` a lot of unnecessary files are committed

2023-02-09 09:14 UTC, AbijithS-aot commented on forms-flow-webcomponent/.gitignore
> +.parcel-cache
removes cache files

2023-02-09 09:15 UTC, AbijithS-aot commented on .github/workflows/forms-flow-web-components-cd.yml
> +      - run: npm ci --force
force installation not necessary removes

2023-02-09 11:19 UTC, sreehari-aot approved these changes
LGTM

2023-02-09 11:19 UTC, sreehari-aot commented on .github/workflows/forms-flow-webcomponents-ci.yml
> +  #     - uses: actions/checkout@v2
remove unused code, keep it if its temporary comment only

2023-02-10 07:00 UTC, AbijithS-aot commented on .github/workflows/forms-flow-webcomponents-ci.yml
> +  #     - uses: actions/checkout@v2
its temporary

2023-02-10 07:01 UTC, merged